import 'package:flutter/material.dart';
import 'sidebar/sdg_item.dart' show SDGItem;

final List<SDGItem> allSDGs = [
  SDGItem(
    id: 1,
    title: '1 ความยากจนต้องหมดไป',
    description: 'ขจัดความยากจนทุกรูปแบบในทุกพื้นที่',
    imagePath: 'assets/images/goal1.png',
    color: Colors.red,
  ),
  SDGItem(
    id: 2,
    title: '2 ขจัดความหิวโหย',
    description: 'ขจัดความหิวโหย บรรลุความมั่นคงทางอาหาร และส่งเสริมเกษตรกรรมที่ยั่งยืน',
    imagePath: 'assets/images/goal2.png',
    color: Colors.orange,
  ),
  SDGItem(
    id: 3,
    title: '3 สุขภาพและความเป็นอยู่ที่ดี',
    description: 'สร้างหลักประกันให้ประชาชนมีสุขภาพและความเป็นอยู่ที่ดีในทุกช่วงวัย',
    imagePath: 'assets/images/goal3.png',
    color: Colors.green,
  ),
  SDGItem(
    id: 4,
    title: '4 การศึกษาที่เท่าเทียม',
    description: 'สร้างหลักประกันว่าทุกคนได้รับการศึกษาที่มีคุณภาพ เท่าเทียม และทั่วถึง',
    imagePath: 'assets/images/goal4.png',
    color: Colors.deepPurple,
  ),
  SDGItem(
    id: 5,
    title: '5 ความเท่าเทียมทางเพศ',
    description: 'บรรลุความเท่าเทียมทางเพศ และเสริมพลังผู้หญิงและเด็กหญิงทุกคน',
    imagePath: 'assets/images/goal5.png',
    color: Colors.pink,
  ),
  SDGItem(
    id: 6,
    title: '6 น้ำสะอาดและสุขาภิบาล',
    description: 'สร้างหลักประกันว่าทุกคนเข้าถึงน้ำสะอาดและการสุขาภิบาล',
    imagePath: 'assets/images/goal6.png',
    color: Colors.cyan,
  ),
  SDGItem(
    id: 7,
    title: '7 พลังงานสะอาด',
    description: 'เข้าถึงพลังงานสะอาดที่เชื่อถือได้ และมีราคาที่จ่ายได้',
    imagePath: 'assets/images/goal7.png',
    color: Colors.yellow[700]!,
  ),
  SDGItem(
    id: 8,
    title: '8 งานที่มีคุณค่าและเศรษฐกิจเติบโต',
    description: 'ส่งเสริมการเติบโตทางเศรษฐกิจที่ยั่งยืน การจ้างงาน และงานที่มีคุณค่า',
    imagePath: 'assets/images/goal8.png',
    color: Colors.deepOrange,
  ),
  SDGItem(
    id: 9,
    title: '9 อุตสาหกรรม นวัตกรรม และโครงสร้างพื้นฐาน',
    description: 'พัฒนาโครงสร้างพื้นฐาน ส่งเสริมนวัตกรรม และอุตสาหกรรมที่ยั่งยืน',
    imagePath: 'assets/images/goal9.png',
    color: Colors.grey,
  ),
  SDGItem(
    id: 10,
    title: '10 ลดความเหลื่อมล้ำ',
    description: 'ลดความเหลื่อมล้ำทั้งภายในและระหว่างประเทศ',
    imagePath: 'assets/images/goal10.png',
    color: Colors.purple,
  ),
  SDGItem(
    id: 11,
    title: '11 เมืองและถิ่นฐานที่ยั่งยืน',
    description: 'ทำให้เมืองปลอดภัย ยืดหยุ่น และยั่งยืน',
    imagePath: 'assets/images/goal11.png',
    color: Colors.amber,
  ),
  SDGItem(
    id: 12,
    title: '12 การบริโภคและการผลิตที่ยั่งยืน',
    description: 'ส่งเสริมการบริโภคและการผลิตอย่างยั่งยืน',
    imagePath: 'assets/images/goal12.png',
    color: Colors.brown,
  ),
  SDGItem(
    id: 13,
    title: '13 รับมือการเปลี่ยนแปลงสภาพภูมิอากาศ',
    description: 'ดำเนินการด่วนเพื่อต่อสู้การเปลี่ยนแปลงสภาพภูมิอากาศและผลกระทบ',
    imagePath: 'assets/images/goal13.png',
    color: Colors.teal,
  ),
  SDGItem(
    id: 14,
    title: '14 การใช้ประโยชน์จากทรัพยากรทางทะเล',
    description: 'อนุรักษ์และใช้ประโยชน์จากมหาสมุทรและทรัพยากรทางทะเลอย่างยั่งยืน',
    imagePath: 'assets/images/goal14.png',
    color: Colors.blue,
  ),
  SDGItem(
    id: 15,
    title: '15 ระบบนิเวศบนบก',
    description: 'ปกป้อง ฟื้นฟู และส่งเสริมการใช้ระบบนิเวศบนบกอย่างยั่งยืน',
    imagePath: 'assets/images/goal15.png',
    color: Colors.lightGreen,
  ),
  SDGItem(
    id: 16,
    title: '16 สันติภาพ ความยุติธรรม และสถาบันที่เข้มแข็ง',
    description: 'ส่งเสริมสังคมที่สงบสุขและไม่แบ่งแยก เข้าถึงความยุติธรรม และสถาบันที่เข้มแข็ง',
    imagePath: 'assets/images/goal16.png',
    color: Colors.indigo,
  ),
  SDGItem(
    id: 17,
    title: '17 ความร่วมมือเพื่อการพัฒนาที่ยั่งยืน',
    description: 'เสริมสร้างความร่วมมือระดับโลกเพื่อการพัฒนาที่ยั่งยืน',
    imagePath: 'assets/images/goal17.png',
    color: Colors.blueGrey,
  ),
];
